name       : haskell-ansi-terminal
version    : 0.10.3
release    : 5
source     :
    - https://hackage.haskell.org/package/ansi-terminal-0.10.3/ansi-terminal-0.10.3.tar.gz : fa2e2e32dfad29835aa7fd442bbe233e07d97e933223a001fe5efa562535b57c
license    : BSD-3-Clause
component  : programming.haskell
summary    : ANSI terminal support for Haskell
description: |
    ANSI terminal support for Haskell: allows cursor movement, screen clearing, color output showing or hiding the cursor, and changing the title. Compatible with Windows and those Unixes with ANSI terminals, but only GHC is supported as a compiler.
builddeps  :
    - haskell-cabal-install
    - haskell-colour-devel
rundeps    :
    - devel:
        - haskell-colour-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
