name       : ansi-terminal
version    : 0.6.2.3
release    : 1
source     :
    - http://hackage.haskell.org/package/ansi-terminal-0.6.2.3/ansi-terminal-0.6.2.3.tar.gz : 4dc02cb53e9ca7c8800bbdfc0337b961e5a945382cd09a6a40c6170126e0ee42
license    : BSD-3-Clause
component  : programming.haskell
summary    : ANSI terminal support for Haskell
description: |
    ANSI terminal support for Haskell: allows cursor movement, screen clearing, color output showing or hiding the cursor, and changing the title. Compatible with Windows and those Unixes with ANSI terminals, but only GHC is supported as a compiler.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
